# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2020 CERN.
# Copyright (C) 2022 RERO.
# Copyright (C) 2022-2024 Graz University of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Tests:
    uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
    with:
      db-service: '[""]'
      search-service: '[""]'
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install uv
        run: pip install uv
      - name: run mypy in venv
        run: |
          mkdir venv && uv venv .venv && source .venv/bin/activate
          uv pip install .[type-check]
          mypy invenio_base
          deactivate
          rm -rf .venv

